import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillMediumSquare,
  AiFillDashboard,
  AiFillFileExcel
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import jeje from "../public/photo 9.jpg";
import code from "../public/coding.png";
import data from "../public/data-research.png";
import writer from "../public/typewriter.png";
import Image from "next/image";
import web1 from "../public/1.png";
import web2 from "../public/2.png";
import web3 from "../public/3.png";
// import data1 from "../public/Dashboard 11.png";
// import data2 from "../public/Dashboard 12.png";
// import data3 from "../public/Story 1.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jajang Jamaludin Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">jajang jamaludin</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/drive/folders/1itobKgH76l82I7_kVo0rVI0X4sa1oCTN?usp=share_link" target="_blank"
                >
                  CV
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Jajang Jamaludin
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Data Analyst | Web Developer | Copywriter
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I am a fresh graduate who has data analyst, programming, & copywriting skills, has sufficient accuracy and self-motivation to work in a team or individually supported by a sense of initiative, responsibility and adaptability, which are advantages that I can contribute to your company .
            </p>
            <div className="text-5xl flex justify-center gap-10 py-4 text-gray-600 dark:text-gray-400">
              <a href="https://www.linkedin.com/in/jajangjamaludin/" target="_blank">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/J-Jamal" target="_blank">
                <AiFillGithub />
              </a>
              <a href="https://medium.com/@jajang-jamaludin" target="_blank">
                <AiFillMediumSquare />
              </a>
              <a href="https://public.tableau.com/app/profile/jjamal" target="_blank">
                <AiFillDashboard />
              </a>
              <a href="https://www.kaggle.com/jjamalin" target="_blank">
                <AiFillFileExcel />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={jeje} />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since I was in college I have studied about the field of web developer, then my writing skills were obtained when I became a content creator on the Student Activity Unit web, and for data analyst skills I got through training on coursera regarding the Google Data Analytics Professional Certificate.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer a variety of services, including Data Analyst, Web Developer, and Copywriter.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image class="mx-auto" src={data} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Data Analyst
              </h3>
              <p className="py-2">
                Turning raw data into valuable information.
              </p>
              <h4 className="py-4 text-teal-600">The analysis tool that I use</h4>
              <p className="text-gray-800 py-1">Tableau</p>
              <p className="text-gray-800 py-1">SQL</p>
              <p className="text-gray-800 py-1">Microsoft Excel</p>
              <p className="text-gray-800 py-1">Python & R</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image class="mx-auto" src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Web Developer
              </h3>
              <p className="py-2">
                Build and provide the best experience for visitors to a site. They manage the creation of page layouts, the style of content on the site, and are also interactive.
              </p>
              <h4 className="py-4 text-teal-600">The Coding Tools I Use</h4>
              <p className="text-gray-800 py-1">Laravel & React</p>
              <p className="text-gray-800 py-1">PHP & Javascript</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">SQL</p>
              <p className="text-gray-800 py-1">Node JS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image class="mx-auto" src={writer} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Copywriter</h3>
              <p className="py-2">
                Write and process content with the aim of inviting potential consumers to buy or use the advertised goods or services.
              </p>
              <h4 className="py-4 text-teal-600">Writing Tools I Use</h4>
              <p className="text-gray-800 py-1">Lektur.Id</p>
              <p className="text-gray-800 py-1">Ejaan.Id</p>
              <p className="text-gray-800 py-1">KBBI Daring</p>
              <p className="text-gray-800 py-1">RimaKata</p>
              <p className="text-gray-800 py-1">PUEBI Daring</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I've been working on several projects since I was in college, whether it's being done alone or also with a team, for more detailed projects, see GitHub, Tableau and Kaggle.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              The following is a website project that I have created, for data analyst and copywriting projects, you can view it on Tableau, Kaggle, and Medium
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                src={web3}
              />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Contact</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              If you are interested in the project I am working on, you can contact me for more information at
              <span className="text-teal-500"> jangudin047@gmail.com </span>
            </p>
          </div>
        </section>

        <footer class="p-4 text-gray-800 rounded-lg shadow md:px-6 md:py-8 dark:text-white">
          <span class="block text-sm text-gray-800 sm:text-center dark:text-gray-200">© 2022 <a href="/" class="hover:underline">JJ™</a>. All Rights Reserved.
          </span>
        </footer>

      </main>
    </div>
  );
}